### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by rishabhpathak359** [TCP-Tech/CodeUtsava8.0#10]
Change the fonts to something that matches our 90's games theme

**Comment by deforeign** [comment]
Sir I want to work on this

**Comment by TheFakeCreator** [comment]
Sir I want to work on this issue

**Comment by TheFakeCreator** [comment]
I had some fonts found and ready for this, you can have a look at them
[8-bit-limit.zip](https://github.com/user-attachments/files/16444520/8-bit-limit.zip)
[bad-mofo.zip](https://github.com/user-attachments/files/16444521/bad-mofo.zip)
[budmo.zip](https://github.com/user-attachments/files/16444522/budmo.zip)
[bulky-pixels.zip](https://github.com/user-attachments/files/16444523/bulky-pixels.zip)
[drive-thru.zip](https://github.com/user-attachments/files/16444524/drive-thru.zip)
[fff-forward.zip](https://github.com/user-attachments/files/16444525/fff-forward.zip)
[joystix.zip](https://github.com/user-attachments/files/16444527/joystix.zip)
[kamikaze.zip](https://github.com/user-attachments/files/16444528/kamikaze.zip)
[karmatic-arcade.zip](https://github.com/user-attachments/files/16444529/karmatic-arcade.zip)
[november.zip](https://github.com/user-attachments/files/16444530/november.zip)
[origami-mommy.zip](https://github.com/user-attachments/files/16444531/origami-mommy.zip)
[pixel.zip](https://github.com/user-attachments/files/16444532/pixel.zip)
[press-start.zip](https://github.com/user-attachments/files/16444533/press-start.zip)
[sho-card-caps.zip](https://github.com/user-attachments/files/16444534/sho-card-caps.zip)
[yoster-island.zip](https://github.com/user-attachments/files/16444535/yoster-island.zip)

**Comment by TheFakeCreator** [comment]
sir do i have to add the licenses as well for the fonts or just the otf and ttf files

**Comment by rishabhpathak359** [comment]
no need for license

**Comment by TheFakeCreator** [comment]
> no need for license

I have added a pull request
