### ISSUE TITLE
About Us Section

### ISSUE THREAD

**Issue by rishabhpathak359** [TCP-Tech/CodeUtsava8.0#107]
Create a about us section , we are planning to design it differently this time, u can show your creativity here. One design example could be- 
![WhatsApp Image 2024-09-06 at 21 49 13_dc40b4b0](https://github.com/user-attachments/assets/e1221879-41cc-481c-803b-88e08d1e4067)
you can modify the headings to maybe who we are ?  what we do ? something like these

again its just for reference if u have any better designs or suggestions you can work accordingly upon them.

**Comment by karanmanglani** [comment]
Sir i will work on this issue
