### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by rishabhpathak359** [TCP-Tech/CodeUtsava8.0#11]
Navbar lists should only include home , about us, merchandise.
Also make it responsive.

**Comment by ArunRathaur1** [comment]
sir, I want to work on this

**Comment by ArunRathaur1** [comment]
I attempted to refactor code from Codeutsava 7.0, which was written in React, for use in HTML. However, I encountered difficulties with transferring the full code and the button animation did not work as expected. To address this, I created a button animation using opacity.
https://github.com/user-attachments/assets/ee74612e-0e92-4694-9043-4be7e6bc8359
