### ISSUE TITLE
Social Links

### ISSUE THREAD

**Issue by rishabhpathak359** [TCP-Tech/CodeUtsava8.0#12]
Include twitter and linkedin links in the social links at the left on the hero section.

**Comment by ArunRathaur1** [comment]
I want this

**Comment by ArunRathaur1** [comment]
Sir, I want to work on this

**Comment by ArunRathaur1** [comment]
![Screenshot 2024-08-03 022245](https://github.com/user-attachments/assets/7f3033a2-bef9-4a25-823d-06b8d359255f)
Added the Social Links, is there any issues I will happy to hear.I used same svg used in codeutsava 7.0

**Comment by rishabhpathak359** [comment]
Open a PR

**Comment by ArunRathaur1** [comment]
ok sir

**Comment by ArunRathaur1** [comment]
sir I have updated the nevbar too, with this code that will also come in PR, what should I do

**Comment by rishabhpathak359** [comment]
ha so what's the issue u have fixed the navbar, right?

**Comment by ArunRathaur1** [comment]
yes, but these are two different issues , so I am worring

**Comment by ArunRathaur1** [comment]
ok sir

**Comment by rishabhpathak359** [comment]
single pr mein hi daaldo koi issue nii h
