### ISSUE TITLE
Game button

### ISSUE THREAD

**Issue by rishabhpathak359** [TCP-Tech/CodeUtsava8.0#13]
A button is to be provided that will re-direct to our game, now its upon your creativity where u place this button such that  visitor's eye catches this button.

**Comment by Shauryacious** [comment]
I have started working on it, will do a pr by today

**Comment by TheFakeCreator** [comment]
will this button be in the homepage?

> A button is to be provided that will re-direct to our game, now its upon your creativity where u place this button such that visitor's eye catches this button.

**Comment by rishabhpathak359** [comment]
> will this button be in the homepage?
> 
> > A button is to be provided that will re-direct to our game, now its upon your creativity where u place this button such that visitor's eye catches this button.

Yes

**Comment by rishabhpathak359** [comment]
> I have started working on it, will do a pr by today

i want it done by the EOD
