### ISSUE TITLE
fix sponsors section, images are missaligned and last few logos breaks as the container translates.

### ISSUE THREAD

**Issue by harshpastor** [TCP-Tech/CodeUtsava8.0#174]
![image](https://github.com/user-attachments/assets/e606184d-8bb4-44ec-b9c4-c8fbb36c9f26)
![image](https://github.com/user-attachments/assets/b982fd64-4e89-466a-bdf2-9e0046e27738)

**Comment by TheFakeCreator** [comment]
working on it

**Comment by TheFakeCreator** [comment]
done 👍 added the PR
