### ISSUE TITLE
fix merch page

### ISSUE THREAD

**Issue by harshpastor** [TCP-Tech/CodeUtsava8.0#175]
give proper spacings and maintain the ratios, 
icon with heading is mis-aligned

**Comment by deforeign** [comment]
Working on this

**Comment by TheFakeCreator** [comment]
done 👍 added the PR

**Comment by deforeign** [comment]
<img width="1350" alt="Screenshot 2024-09-17 at 12 18 48 AM" src="https://github.com/user-attachments/assets/562a0f05-bf36-4fb1-ba51-1049df80f3a0">
