### ISSUE TITLE
Keyboard events in the intro screen

### ISSUE THREAD

**Issue by TheFakeCreator** [TCP-Tech/CodeUtsava8.0#36]
The enter button in the intro screen should get fired if we press the enter button on our keyboard.

**Comment by rishabhpathak359** [comment]
Fix it yourself.

**Comment by TheFakeCreator** [comment]
> Fix it yourself.

Ya😅 I was just asking if we are going to implement that or not

**Comment by rishabhpathak359** [comment]
> > Fix it yourself.
> 
> Ya😅 I was just asking if we are going to implement that or not

Yes

**Comment by TheFakeCreator** [comment]
i've dropped a pull request.
