### ISSUE TITLE
Music

### ISSUE THREAD

**Issue by rishabhpathak359** [TCP-Tech/CodeUtsava8.0#39]
a click sound on pressing enter button and then maybe a swoosh kind of sound for clouds closing in and then a sound that matches with the bg like water falling and birds chirping and provide a button for controlling the play-pause of the music . You can take reference from the 7.0 website , like there was a pumpkin container based on halloween theme , this time also a similar container based on our theme is to be provided (old monitor screen , slot machine) or anything similar.

**Comment by TheFakeCreator** [comment]
I have found some sound track for the environment and tweaked some of them a little bit using a bitcrusher to match the theme of our website. Particularly I made two tracks one is the idle background theme which is 8bit and sampled at 8000hz and an ambience track which is sampled at 44100hz for better sound.

https://drive.google.com/file/d/1U4rPnH1n2AamV8GT1q93aqLHfGK-NJ9H/view?usp=sharing
https://drive.google.com/file/d/1yGbZH8zxRR-2WQr94jMFOS4wOqiyOdcH/view?usp=sharing

they together sound good.

**Comment by rishabhpathak359** [comment]
> I have found some sound track for the environment and tweaked some of them a little bit using a bitcrusher to match the theme of our website. Particularly I made two tracks one is the idle background theme which is 8bit and sampled at 8000hz and an ambience track which is sampled at 44100hz for better sound.
> 
> https://drive.google.com/file/d/1U4rPnH1n2AamV8GT1q93aqLHfGK-NJ9H/view?usp=sharing https://drive.google.com/file/d/1yGbZH8zxRR-2WQr94jMFOS4wOqiyOdcH/view?usp=sharing
> 
> they together sound good.

Sample them together

**Comment by TheFakeCreator** [comment]
> > I have found some sound track for the environment and tweaked some of them a little bit using a bitcrusher to match the theme of our website. Particularly I made two tracks one is the idle background theme which is 8bit and sampled at 8000hz and an ambience track which is sampled at 44100hz for better sound.
> > 
> > https://drive.google.com/file/d/1U4rPnH1n2AamV8GT1q93aqLHfGK-NJ9H/view?usp=sharing https://drive.google.com/file/d/1yGbZH8zxRR-2WQr94jMFOS4wOqiyOdcH/view?usp=sharing
> > 
> > they together sound good.
> 
> Sample them together

Okk

**Comment by TheFakeCreator** [comment]
https://drive.google.com/file/d/1lKV4eBRCk_a1AlD4sOIwRsAaG-q9D8bU/view?usp=sharing

**Comment by TheFakeCreator** [comment]
I’ve completed all the major JavaScript work for the music, with only the sound effects for clicks and the cloud animations remaining. Despite searching extensively, I haven’t found a sound that fits our theme perfectly. Additionally, I still need to work on the CSS for the control buttons. Overall, the website is shaping up well and looks like this so far:

https://github.com/user-attachments/assets/fe7cca5e-197b-421a-9048-dc9fea2fb148

**Comment by rishabhpathak359** [comment]
Keep a single button the speaker one looks fine keep that only.

**Comment by TheFakeCreator** [comment]
dropped a pr

**Comment by rishabhpathak359** [comment]
Modifiy the specifications a bit right now audio is sampled at a high bit rate and frequency ,local pe its working fine but on production i think it'll cause issue .
https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Audio_codecs#mp3_mpeg-1_audio_layer_iii

refer to the specifications mentioned here.
