### ISSUE TITLE
Navbar is not optimized for all screen sizes

### ISSUE THREAD

**Issue by TheFakeCreator** [TCP-Tech/CodeUtsava8.0#56]
The navbar is not styled correctly. In smaller screen sizes it comes back to its previous version.
![Screenshot (72)](https://github.com/user-attachments/assets/baae89b4-076c-4df8-b1f1-44974c9d895c)
![Screenshot (73)](https://github.com/user-attachments/assets/1670a49d-4e6e-43b9-a5fd-db7bb32c435f)

**Comment by karanmanglani** [comment]
sir i have created a pull request regarding this issue
