### ISSUE TITLE
Last Year's Participation section

### ISSUE THREAD

**Issue by ayushshukla011** [TCP-Tech/CodeUtsava8.0#86]
Create a Last Year's Participation section. Ensure It matches with the website theme. Use the same data for now.
last year's reference.
![Screenshot 2024-08-24 230749](https://github.com/user-attachments/assets/e0165a00-d43f-4e8e-b400-d742e930d618)

No need to keep same as Last year's. Creativity is welcomed. Collaborate with other's to deliver the best.

**Comment by ArunRathaur1** [comment]
I am intrested in this

**Comment by ArunRathaur1** [comment]
sir ,completed the task and open the pull request
